version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.6
    container_name: elasticsearch_5.6.6
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./es/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
      - ./sslcert:/usr/share/elasticsearch/config/certs
      - /var/log/elasticsearch:/usr/share/elasticsearch/logs
      #- ./es/plugins:/usr/share/elasticsearch/plugins
    networks:
      static-network:
        ipv4_address: 172.20.128.2

    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 2g
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.6
    container_name: kibana_566
    networks:
      static-network:
        ipv4_address: 172.20.128.3

    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./sslcert/all-truststore.pem:/etc/security/interset/sslcert/all-truststore.pem
      - /var/log/kibana:/var/log/kibana
    ports:
      - 5601:5601
volumes:
  esdata:
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          #docker-compose v3+ do not use ip_range
          ip_range: 172.28.5.0/24
